name: check-build

on: 
  push:
    tags:
    - 'v*'

jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: list
      run: ls -a $GITHUB_WORKSPACE
    - name: zip test
      run: |
        echo "---- dump output data ----"
        mkdir -p /tmp/test/usr
        sudo chmod 666 /tmp/test
        sudo chmod 666 /tmp/test/usr
        sudo cp -r $GITHUB_WORKSPACE/README.md /tmp/test/usr/
        sudo zip -r /tmp/test/test.zip /tmp/test/usr
        sudo chmod 666 test.zip
        echo "---- dump zip file ----"
        ls -l
    - name: docker setup
      uses: docker://alpine:3.10
      with:
        entrypoint: /github/workspace/.github/workflows/build_entrypoint.sh
    - name: create zip file
      run: |
        echo "---- dump output data ----"
        ls -l $GITHUB_WORKSPACE/dist/usr/local/*
        mkdir -p /tmp/cfd/usr
        sudo chmod 666 /tmp/cfd
        sudo chmod 666 /tmp/cfd/usr
        sudo cp -r $GITHUB_WORKSPACE/dist/usr /tmp/cfd/usr
        sudo zip -r /tmp/cfd/cfd.zip /tmp/cfd/usr
        sudo chmod 666 cfd.zip
        echo "---- dump zip file ----"
        ls -l
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /tmp/cfd/cfd.zip
        asset_name: cfd-${{ github.ref }}-alpine_x86_64.zip
        asset_content_type: application/zip

