name: check-build

on: 
  push:
    branches:
    - master
    - develop
    - testing/*
    - release/*
  pull_request:
    branches:
    - master
    - develop
    - testing/*

jobs:
  cmake-win:
    name: cmake build-win
    runs-on: windows-latest
    strategy:
      matrix:
        generator: [vs2019, mingw]

    steps:
    - uses: actions/checkout@v1
    - name: cmake_version
      run: cmake --version
    - name: cmake_generage-vs2019
      if: matrix.generator == 'vs2019'
      run: cmake -S . -B build -G "Visual Studio 16 2019"
    - name: cmake_generage-mingw
      if: matrix.generator == 'mingw'
      run: cmake -S . -B build -G "MSYS Makefiles"
    - name: cmake_configure
      run: cmake -DENABLE_SHARED=on -DENABLE_TESTS=off --build build
    - name: cmake_build
      run: cmake --build build --config Release

  cmake-mac:
    name: cmake build-mac
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: cmake_version
      run: cmake --version
    - name: cmake_generage-macos
      run: |
        cmake -S . -B build -G "Unix Makefiles"
        cmake -DENABLE_SHARED=on --build build
    - name: cmake_build
      run: cmake --build build --config Release
    - name: ctest
      run: |
        cd build
        ctest -C Release

  doxygen-ubuntu:
    name: doxygen-ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install_doxygen
      run: sudo apt install doxygen graphviz
    - name: doxygen_check
      run: |
        cd doc
        doxygen Doxyfile_quiet_all

  docker-build:
    name: docker-build
    runs-on: ubuntu-latest

    steps:
    - name: docker setup
      uses: docker://alpine:3.10
    - name: install
      run: apk add --update --no-cache musl gcc g++ make git cmake nodejs
    - name: checkout
      uses: actions/checkout@v1
    - name: cmake_version
      run: cmake --version
    - name: cmake_generage
      run: |
        mkdir /tmp/dist
        mkdir build
        cd build
        cmake .. -DENABLE_SHARED=on -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=off -DENABLE_JS_WRAPPER=off -DENABLE_CAPI=on -DTARGET_RPATH="/usr/local/lib;/usr/local/lib64"
        make
        make install DESTDIR=/tmp/dist 
        ls /tmp/dist
        ls /tmp/dist/usr
        ls /tmp/dist/usr/local
        ls /tmp/dist/usr/local/lib64
        ls /usr/local/lib64
    - name: doxygen_check
      run: |
        cd doc
        doxygen Doxyfile_quiet_all
