name: develop pre-merge check

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  cmake-win-test:
    name: cmake build-win
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
        generator: ['MSYS Makefiles']
        shared: [on, off]
        include:
          - os: windows-2019
            shared: on
            generator: 'Visual Studio 16 2019'
          - os: windows-2019
            shared: off
            generator: 'Visual Studio 16 2019'
          - os: windows-2022
            shared: on
            generator: 'Visual Studio 17 2022'
          - os: windows-2022
            shared: off
            generator: 'Visual Studio 17 2022'

    steps:
      - uses: actions/checkout@v4
      - name: cmake_version
        run: cmake --version
      - name: cmake_generage
        run: cmake -S . -B build -G "${{ matrix.generator }}" -DENABLE_SHARED=${{ matrix.shared }} -DENABLE_TESTS=on
      - name: cmake_build
        run: cmake --build build --config Release --parallel 4
      - name: ctest
        run: |
          cd build
          ctest -C Release --output-on-failure

  cmake-mac-test:
    name: cmake build-mac
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]
        include:
          - os: macos-13
            xcode_version: '14.3.1'
          - os: macos-14
            xcode_version: '15.4'
          - os: macos-15
            xcode_version: '16.1'

    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_${{matrix.xcode_version}}.app/Contents/Developer'
      - name: Show Xcode version
        run: xcodebuild -version
      - name: cmake_version
        run: cmake --version
      - name: cmake_generage-macos
        run: cmake -S . -B build -G "Unix Makefiles" -DENABLE_SHARED=on -DENABLE_ELEMENTS=on
      - name: cmake_build
        run: cmake --build build --config Release --parallel 4
      - name: ctest
        run: |
          cd build
          ctest -C Release --output-on-failure
      - name: lint_check
        run: ./tools/lint_quiet.sh

  cmake-ubuntu-test:
    name: cmake build-ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
        shared: [on, off]
        elements: [on]
        include:
          - os: ubuntu-22.04
            elements: off

    steps:
      - uses: actions/checkout@v4
      - name: dump version
        run: |
          cmake --version
          gcc --version
      - name: cmake_configure
        run: |
          cmake -S . -B build -G "Unix Makefiles" -DENABLE_SHARED=${{ matrix.shared }} -DENABLE_ELEMENTS=${{ matrix.elements }} -DTARGET_RPATH=./build/Release
      - name: cmake-build
        run: cmake --build build --config Release --parallel 4
      - name: lint_check
        run: ./tools/lint_quiet.sh
      - name: test
        run: |
          cd build
          ctest -C Release --output-on-failure
          cd ..

  doxygen-ubuntu:
    name: doxygen-check
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: install_doxygen
        run: sudo apt install doxygen graphviz
      - name: doxygen_check
        run: |
          cd doc
          doxygen Doxyfile_quiet_all
